<?php

namespace BybitApi\Enums;

enum LogType: string
{
    case TRANSFER_IN = 'TRANSFER_IN';
    case TRANSFER_OUT = 'TRANSFER_OUT';
    case TRADE = 'TRADE';
    case SETTLEMENT = 'SETTLEMENT';
    case DELIVERY = 'DELIVERY';
    case LIQUIDATION = 'LIQUIDATION';
    case ADL = 'ADL';
    case AIRDROP = 'AIRDROP';
    case BONUS = 'BONUS';
    case BONUS_RECOLLECT = 'BONUS_RECOLLECT';
    case FEE_REFUND = 'FEE_REFUND';
    case INTEREST = 'INTEREST';
    case CURRENCY_BUY = 'CURRENCY_BUY';
    case CURRENCY_SELL = 'CURRENCY_SELL';
    case BORROWED_AMOUNT_INS_LOAN = 'BORROWED_AMOUNT_INS_LOAN';
    case PRINCIPLE_REPAYMENT_INS_LOAN = 'PRINCIPLE_REPAYMENT_INS_LOAN';
    case INTEREST_REPAYMENT_INS_LOAN = 'INTEREST_REPAYMENT_INS_LOAN';
    case AUTO_SOLD_COLLATERAL_INS_LOAN = 'AUTO_SOLD_COLLATERAL_INS_LOAN';
    case AUTO_BUY_LIABILITY_INS_LOAN = 'AUTO_BUY_LIABILITY_INS_LOAN';
    case AUTO_PRINCIPLE_REPAYMENT_INS_LOAN = 'AUTO_PRINCIPLE_REPAYMENT_INS_LOAN';
    case AUTO_INTEREST_REPAYMENT_INS_LOAN = 'AUTO_INTEREST_REPAYMENT_INS_LOAN';
    case TRANSFER_IN_INS_LOAN = 'TRANSFER_IN_INS_LOAN';
    case TRANSFER_OUT_INS_LOAN = 'TRANSFER_OUT_INS_LOAN';
    case SPOT_REPAYMENT_SELL = 'SPOT_REPAYMENT_SELL';
    case SPOT_REPAYMENT_BUY = 'SPOT_REPAYMENT_BUY';
    case TOKENS_SUBSCRIPTION = 'TOKENS_SUBSCRIPTION';
    case TOKENS_REDEMPTION = 'TOKENS_REDEMPTION';
    case AUTO_DEDUCTION = 'AUTO_DEDUCTION';
    case FLEXIBLE_STAKING_SUBSCRIPTION = 'FLEXIBLE_STAKING_SUBSCRIPTION';
    case FLEXIBLE_STAKING_REDEMPTION = 'FLEXIBLE_STAKING_REDEMPTION';
    case FIXED_STAKING_SUBSCRIPTION = 'FIXED_STAKING_SUBSCRIPTION';
    case PREMARKET_TRANSFER_OUT = 'PREMARKET_TRANSFER_OUT';
    case PREMARKET_DELIVERY_SELL_NEW_COIN = 'PREMARKET_DELIVERY_SELL_NEW_COIN';
    case PREMARKET_DELIVERY_BUY_NEW_COIN = 'PREMARKET_DELIVERY_BUY_NEW_COIN';
    case PREMARKET_DELIVERY_PLEDGE_PAY_SELLER = 'PREMARKET_DELIVERY_PLEDGE_PAY_SELLER';
    case PREMARKET_DELIVERY_PLEDGE_BACK = 'PREMARKET_DELIVERY_PLEDGE_BACK';
    case PREMARKET_ROLLBACK_PLEDGE_BACK = 'PREMARKET_ROLLBACK_PLEDGE_BACK';
    case PREMARKET_ROLLBACK_PLEDGE_PENALTY_TO_BUYER = 'PREMARKET_ROLLBACK_PLEDGE_PENALTY_TO_BUYER';
    case CUSTODY_NETWORK_FEE = 'CUSTODY_NETWORK_FEE';
    case CUSTODY_SETTLE_FEE = 'CUSTODY_SETTLE_FEE';
    case CUSTODY_LOCK = 'CUSTODY_LOCK';
    case CUSTODY_UNLOCK = 'CUSTODY_UNLOCK';
    case CUSTODY_UNLOCK_REFUND = 'CUSTODY_UNLOCK_REFUND';
    case LOANS_BORROW_FUNDS = 'LOANS_BORROW_FUNDS';
    case LOANS_PLEDGE_ASSET = 'LOANS_PLEDGE_ASSET';
    case BONUS_TRANSFER_IN = 'BONUS_TRANSFER_IN';
    case BONUS_TRANSFER_OUT = 'BONUS_TRANSFER_OUT';
    case PEF_TRANSFER_IN = 'PEF_TRANSFER_IN';
    case PEF_TRANSFER_OUT = 'PEF_TRANSFER_OUT';
    case PEF_PROFIT_SHARE = 'PEF_PROFIT_SHARE';

    case OTHER = 'OTHER';
}
